title: Kendra Devereux
logo: /assets/headshot.jpg
description: GIS and Data Science Portfolio
[LinkedIn Profile](https://www.linkedin.com/in/kendra-devereux/)
[Resume](https://devereuxresume.tiiny.site/)
#show_downloads: true
theme: jekyll-theme-minimal
