title: Kendra Devereux
logo: /assets/headshot.jpg
description: GIS and Data Science Portfolio 
description: <a href="https://www.linkedin.com/in/kendra-devereux/">LinkedIn</a> 
description: <a href="https://devereuxresume.tiiny.site/">Resume</a>
#show_downloads: true
theme: jekyll-theme-minimal
