title: Kendra Devereux
logo: /assets/headshot.jpg
description: GIS and Data Science Portfolio <a href="https://www.linkedin.com/in/kendra-devereux/">👔 LinkedIn</a>
#show_downloads: true
theme: jekyll-theme-minimal
